[phases.setup]
nixPkgs = ["jdk8", "maven"]

[phases.build]
cmds = [
    "cd ../FRAMEWORK && mvn clean install -DskipTests",
    "cd ../TEST && mvn clean package -DskipTests"
]

[start]
cmd = "java -jar target/spring-init-test-1.0.0.jar"